recipes-backports: add elfutils v0.191
While kirkstone meanwhile announces support for Ubuntu 24.04 LTS
as compatible platform, the older elfutils in kirkstone fail to
build due to a curl deprecation warning on this distro:

-8<----
 ../../elfutils-0.186/debuginfod/debuginfod-client.c:1158:11:
 error: ‘CURLINFO_CONTENT_LENGTH_DOWNLOAD’ is deprecated: since 7.55.0.
 Use CURLINFO_CONTENT_LENGTH_DOWNLOAD_T [-Werror=deprecated-declarations]
-------

This backport imports elfutils from scarthgap branch.

Signed-off-by: Michael Heimpold <mhei@heimpold.de>